/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'trajectory-data': TrajectoryDatum;
    'engagement-cases': EngagementCase;
    research: Research;
    'strategic-submissions': StrategicSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'trajectory-data': TrajectoryDataSelect<false> | TrajectoryDataSelect<true>;
    'engagement-cases': EngagementCasesSelect<false> | EngagementCasesSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    'strategic-submissions': StrategicSubmissionsSelect<false> | StrategicSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'theme-settings': ThemeSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'theme-settings': ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  navigation: {
    navLabel: string;
    showInNav?: boolean | null;
    navOrder?: number | null;
  };
  layout: (
    | HomeHeroBlock
    | CorePillarsBlock
    | PhilosophyStatementBlock
    | CapitalDomainsBlock
    | TrajectoryViewerBlock
    | RiskArchitectureBlock
    | EngagementNarrativesBlock
    | FounderProfileBlock
    | ContactModuleBlock
  )[];
  seo: {
    title: string;
    description: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  brandName: string;
  positioning: string;
  primaryCTA: {
    label: string;
    url: string;
  };
  secondaryCTA: {
    label: string;
    url: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorePillarsBlock".
 */
export interface CorePillarsBlock {
  heading?: string | null;
  cards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'corePillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyStatementBlock".
 */
export interface PhilosophyStatementBlock {
  coreSentence: string;
  modules?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'philosophyStatement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapitalDomainsBlock".
 */
export interface CapitalDomainsBlock {
  heading?: string | null;
  domains?:
    | {
        title: string;
        line1: string;
        line2: string;
        line3: string;
        readMoreLabel?: string | null;
        readMoreUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'capitalDomains';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrajectoryViewerBlock".
 */
export interface TrajectoryViewerBlock {
  heading: string;
  description: string;
  trajectoryData: number | TrajectoryDatum;
  id?: string | null;
  blockName?: string | null;
  blockType: 'trajectoryViewer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trajectory-data".
 */
export interface TrajectoryDatum {
  id: number;
  title: string;
  active?: boolean | null;
  periods: {
    period: '3Y' | '1Y' | '3M' | 'YTD';
    points: {
      label: string;
      starRingCapital: number;
      globalEquityBenchmark: number;
      riskFreeBenchmark: number;
      id?: string | null;
    }[];
    metrics: {
      cagr: number;
      maxDrawdown: number;
      volatility: number;
      sharpeRatio: number;
    };
    id?: string | null;
  }[];
  complianceStatements?:
    | {
        statement: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RiskArchitectureBlock".
 */
export interface RiskArchitectureBlock {
  heading: string;
  layers?:
    | {
        layerName: string;
        purpose: string;
        bullets?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'riskArchitecture';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EngagementNarrativesBlock".
 */
export interface EngagementNarrativesBlock {
  heading: string;
  description?: string | null;
  cases: (number | EngagementCase)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'engagementNarratives';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-cases".
 */
export interface EngagementCase {
  id: number;
  year: number;
  strategicName: string;
  summaryLines: {
    line: string;
    id?: string | null;
  }[];
  resultSignature: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FounderProfileBlock".
 */
export interface FounderProfileBlock {
  heading: string;
  narrative: string;
  capabilityPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  portrait?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'founderProfile';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactModuleBlock".
 */
export interface ContactModuleBlock {
  heading: string;
  email: string;
  alignmentCopy: string;
  enableForm?: boolean | null;
  formFields?:
    | {
        label: string;
        type: 'text' | 'email' | 'textarea';
        placeholder?: string | null;
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactModule';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  body: string;
  showOnSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Strategic collaboration leads submitted from the public website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strategic-submissions".
 */
export interface StrategicSubmission {
  id: number;
  status: 'new' | 'in_review' | 'qualified' | 'archived';
  priority?: ('high' | 'normal' | 'low') | null;
  contactName: string;
  contactEmail?: string | null;
  organization?: string | null;
  phone?: string | null;
  locale?: ('en' | 'zh') | null;
  sourcePage?: string | null;
  message?: string | null;
  submittedAt: string;
  entries?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal follow-up notes (not visible to public users).
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'trajectory-data';
        value: number | TrajectoryDatum;
      } | null)
    | ({
        relationTo: 'engagement-cases';
        value: number | EngagementCase;
      } | null)
    | ({
        relationTo: 'research';
        value: number | Research;
      } | null)
    | ({
        relationTo: 'strategic-submissions';
        value: number | StrategicSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  navigation?:
    | T
    | {
        navLabel?: T;
        showInNav?: T;
        navOrder?: T;
      };
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        corePillars?: T | CorePillarsBlockSelect<T>;
        philosophyStatement?: T | PhilosophyStatementBlockSelect<T>;
        capitalDomains?: T | CapitalDomainsBlockSelect<T>;
        trajectoryViewer?: T | TrajectoryViewerBlockSelect<T>;
        riskArchitecture?: T | RiskArchitectureBlockSelect<T>;
        engagementNarratives?: T | EngagementNarrativesBlockSelect<T>;
        founderProfile?: T | FounderProfileBlockSelect<T>;
        contactModule?: T | ContactModuleBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  brandName?: T;
  positioning?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorePillarsBlock_select".
 */
export interface CorePillarsBlockSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhilosophyStatementBlock_select".
 */
export interface PhilosophyStatementBlockSelect<T extends boolean = true> {
  coreSentence?: T;
  modules?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapitalDomainsBlock_select".
 */
export interface CapitalDomainsBlockSelect<T extends boolean = true> {
  heading?: T;
  domains?:
    | T
    | {
        title?: T;
        line1?: T;
        line2?: T;
        line3?: T;
        readMoreLabel?: T;
        readMoreUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrajectoryViewerBlock_select".
 */
export interface TrajectoryViewerBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  trajectoryData?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RiskArchitectureBlock_select".
 */
export interface RiskArchitectureBlockSelect<T extends boolean = true> {
  heading?: T;
  layers?:
    | T
    | {
        layerName?: T;
        purpose?: T;
        bullets?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EngagementNarrativesBlock_select".
 */
export interface EngagementNarrativesBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  cases?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FounderProfileBlock_select".
 */
export interface FounderProfileBlockSelect<T extends boolean = true> {
  heading?: T;
  narrative?: T;
  capabilityPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  portrait?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactModuleBlock_select".
 */
export interface ContactModuleBlockSelect<T extends boolean = true> {
  heading?: T;
  email?: T;
  alignmentCopy?: T;
  enableForm?: T;
  formFields?:
    | T
    | {
        label?: T;
        type?: T;
        placeholder?: T;
        required?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trajectory-data_select".
 */
export interface TrajectoryDataSelect<T extends boolean = true> {
  title?: T;
  active?: T;
  periods?:
    | T
    | {
        period?: T;
        points?:
          | T
          | {
              label?: T;
              starRingCapital?: T;
              globalEquityBenchmark?: T;
              riskFreeBenchmark?: T;
              id?: T;
            };
        metrics?:
          | T
          | {
              cagr?: T;
              maxDrawdown?: T;
              volatility?: T;
              sharpeRatio?: T;
            };
        id?: T;
      };
  complianceStatements?:
    | T
    | {
        statement?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "engagement-cases_select".
 */
export interface EngagementCasesSelect<T extends boolean = true> {
  year?: T;
  strategicName?: T;
  summaryLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  resultSignature?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  showOnSite?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strategic-submissions_select".
 */
export interface StrategicSubmissionsSelect<T extends boolean = true> {
  status?: T;
  priority?: T;
  contactName?: T;
  contactEmail?: T;
  organization?: T;
  phone?: T;
  locale?: T;
  sourcePage?: T;
  message?: T;
  submittedAt?: T;
  entries?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  primaryNavCTA?: {
    label?: string | null;
    url?: string | null;
  };
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  footerNote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings".
 */
export interface ThemeSetting {
  id: number;
  backgroundColor: string;
  backgroundAccentColor: string;
  textColor: string;
  mutedTextColor: string;
  accentGoldColor: string;
  buttonStyle: {
    variant: 'rounded' | 'outline' | 'glow';
    radius: number;
    glowIntensity: number;
  };
  typography: {
    fontPreset: 'institutional' | 'contemporary';
    bodyWeight: number;
    headingWeight: number;
  };
  logo?: (number | null) | Media;
  orbitEffect: {
    enabled?: boolean | null;
    speed: number;
    opacity: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  primaryNavCTA?:
    | T
    | {
        label?: T;
        url?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme-settings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  backgroundColor?: T;
  backgroundAccentColor?: T;
  textColor?: T;
  mutedTextColor?: T;
  accentGoldColor?: T;
  buttonStyle?:
    | T
    | {
        variant?: T;
        radius?: T;
        glowIntensity?: T;
      };
  typography?:
    | T
    | {
        fontPreset?: T;
        bodyWeight?: T;
        headingWeight?: T;
      };
  logo?: T;
  orbitEffect?:
    | T
    | {
        enabled?: T;
        speed?: T;
        opacity?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'research';
          value: number | Research;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}